name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.MODULE_TOKEN }}  # Pass the token as an environment variable

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build project
        run: |
          echo "const token = '${GITHUB_TOKEN}';" > config.js  # Inject the token into a config file
          npm run build